spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=labeling;encrypt=true;trustServerCertificate=true}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${SPRING_DATASOURCE_USERNAME:label_app}
    password: ${SPRING_DATASOURCE_PASSWORD:Labeling@2026!}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
